version: "3.9"

services:
  node_app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5050:5050
    env_file:
      - .env